### ISSUE TITLE
4-a-  TAREA  ASIGANDA :   Dario y Carla

### ISSUE THREAD

**Issue by WayarCarla** [EMTSTISPC/Grupo2#12]
Punto 4. a . Subcarpetas

**Comment by WayarCarla** [comment]
[PIC.pdf](https://github.com/EMTSTISPC/Grupo2/files/9254661/PIC.pdf)

**PRIMER AVANCE DE LAS PRIMERAS 4 SUBCARPETAS DEL PIC**

**Comment by dr-arriola** [comment]
PRIMER AVANCE DE LAS SEGUNDAS 4 SUBCARPETAS DEL AVR.


[AVR.pdf](https://github.com/EMTSTISPC/Grupo2/files/9256084/AVR.pdf)
