### ISSUE TITLE
Informe SoC ESP

### ISSUE THREAD

**Issue by NataliaGalliani** [EMTSTISPC/Grupo2#2]
Completar con los demás modelos (solo está Nodemcu)

**Comment by WayarCarla** [comment]
[ESP8266_GRUPO2.pdf](https://github.com/EMTSTISPC/Grupo2/files/9238199/ESP8266_GRUPO2.pdf)

**Comment by WayarCarla** [comment]
[ESP32_GRUPO2.pdf](https://github.com/EMTSTISPC/Grupo2/files/9238206/ESP32_GRUPO2.pdf)
