### ISSUE TITLE
Código de ejemplo para ESP

### ISSUE THREAD

**Issue by NataliaGalliani** [EMTSTISPC/Grupo2#3]
Código de ejemplo para las características relevantes del ESP

**Comment by WayarCarla** [comment]
[EJEMPLO_1_ESP8266_IDE_ARDUINO.pdf](https://github.com/EMTSTISPC/Grupo2/files/9230553/EJEMPLO_1_ESP8266_IDE_ARDUINO.pdf)

**Comment by WayarCarla** [comment]
[EJEMPLO_2_ESP8266_WIFI.pdf](https://github.com/EMTSTISPC/Grupo2/files/9230789/EJEMPLO_2_ESP8266_WIFI.pdf)
